language: python
python:
    - 3.7
    - 3.8
before_install:
    - python --version
    - pip install -U pip
    - pip install codecov
install:
    - pip install ".[test]"
    # - pip install -r requirements.txt
script:
    - python -m unittest test_withdraw.py
    - coverage run test_withdraw.py
after_success:
    - codecov
    # - bash <(curl -s https://codecov.io/bash)